ballerina-lang/plugin-intellij

README.md

Fix numbering issue in the ReadMe

---

src/main/resources/META-INF/plugin.xml

Change vendor email

---

README.md

This commit will update the instructions on how to install the plugin to IDEA since the steps are bit different in macOS.
Resolves #169

Update the instructions in ReadMe

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtil.java

This PR will update the completion contributor to add some missing keywords and suggestions.

Update completion contributor

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaConstants.java
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaConfigurableProvider.java
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaLibrariesConfigurable.java
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaLibrariesConfigurableProvider.java
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaModuleAwareConfigurable.java
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaModuleSettingsConfigurable.java
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaModuleSettingsUI.form
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaModuleSettingsUI.java
src/main/java/org/ballerinalang/plugins/idea/configuration/ListenableHideableDecorator.java
src/main/java/org/ballerinalang/plugins/idea/project/BallerinaApplicationLibrariesService.java
src/main/java/org/ballerinalang/plugins/idea/project/BallerinaLibrariesService.java
src/main/java/org/ballerinalang/plugins/idea/project/BallerinaLibraryState.java
src/main/java/org/ballerinalang/plugins/idea/project/BallerinaModuleLibrariesInitializer.java
src/main/java/org/ballerinalang/plugins/idea/project/BallerinaModuleSettings.java
src/main/java/org/ballerinalang/plugins/idea/project/BallerinaProjectLibrariesService.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaEnvironmentUtil.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaPathModificationTracker.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkLibraryPresentationProvider.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkService.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkUtil.java
src/main/resources/META-INF/plugin.xml

This PR will add support to add a user repository through **BALLERINA_REPOSITORY** environment variable.
Resolves #98

Add Ballerina Repository support

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaTypes.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaBlock.java

Fix elementValuePairs not formatting properly issue

---

README.md

Add release version schema table

---

src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkUtil.java

Update version regex

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

This PR fixes elements not resolving properly in a package issue.
Resolves #185

Fix elements not resolving properly issue

---

src/main/java/org/ballerinalang/plugins/idea/project/BallerinaModuleLibrariesInitializer.java

Fix issue in Ballerina User Repository

---

src/main/java/org/ballerinalang/plugins/idea/run/configuration/BallerinaConsoleFolding.java
src/main/resources/META-INF/plugin.xml

This PR will add console folding support which will hide Ballerina run commands by default.
Resolves #187

Add console folding support

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/codeinsight/editoractions/BallerinaQuoteHandler.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtil.java
src/main/java/org/ballerinalang/plugins/idea/completion/BracesInsertHandler.java
src/main/java/org/ballerinalang/plugins/idea/editor/BallerinaParameterInfoHandler.java
src/main/java/org/ballerinalang/plugins/idea/psi/AnnotationAttributeValueNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/ActionInvocationReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

This PR adds few new keywords and improves code completion logic.

Update code completion

---

src/main/java/org/ballerinalang/plugins/idea/psi/ActionDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ConnectorBodyNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ConnectorNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/FunctionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ResourceDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/StatementReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/VariableReference.java
src/main/java/org/ballerinalang/plugins/idea/usage/BallerinaFindUsageProvider.java

Add Ctrl+Click find usage support

---

src/main/resources/META-INF/plugin.xml

This PR updates change notes in the plugin.xml.

Update change notes

---

src/main/gen/org/ballerinalang/plugins/idea/grammar/BallerinaParser.java
src/main/java/org/ballerinalang/plugins/idea/BallerinaTypes.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaBlock.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaFormattingModelBuilder.java
src/main/java/org/ballerinalang/plugins/idea/grammar/Ballerina.g4

Fix annotation definition not formatting issue

---

src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

Fix structs not resolving issue

---

src/main/resources/liveTemplates/Ballerina.xml

Update live templates

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java

This PR fixes the issue of resource keyword available at file level issue.
Resolves #218

Fix resource keyword issue

---

src/main/resources/META-INF/plugin.xml

Update plugin description

---

src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java

Fix the definition not highlighting issue

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/usage/BallerinaFindUsageProvider.java

This commit will,
1) Fix functions in other packages not suggesting issue.
2) Remove suggesting constants in other packages since grammar is not yet supported.

Fix issues related to completion

---

src/main/java/org/ballerinalang/plugins/idea/psi/ServiceDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaItemPresentation.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaRootPresentation.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaStructureViewElement.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaStructureViewModel.java

Fix issues in structure view

---

src/main/java/org/ballerinalang/plugins/idea/psi/FunctionNode.java

Fix presentation issue

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/editor/BallerinaFoldingBuilder.java
src/main/java/org/ballerinalang/plugins/idea/psi/StructBodyNode.java
src/main/resources/META-INF/plugin.xml
src/test/java/BallerinaFoldingTest.java
src/test/java/BallerinaParsingTest.java
src/test/resources/testData/folding/Connector.bal
src/test/resources/testData/folding/Function.bal
src/test/resources/testData/folding/Service.bal
src/test/resources/testData/folding/Struct.bal

This PR adds code folding support for functions, services, etc.
Resolves #183

Add code folding support

---

src/main/java/org/ballerinalang/plugins/idea/spellchecker/BallerinaIdentifierTokenizer.java
src/main/java/org/ballerinalang/plugins/idea/spellchecker/BallerinaSpellcheckingStrategy.java
src/main/resources/META-INF/plugin.xml
src/test/java/BallerinaSpellCheckingTest.java
src/test/resources/testData/spellchecking/Sample.bal

This PR adds spellchecking support to Ballerina source files.
Resolves #228

Add spell checking support

---

.gitmodules

Change sub module url from SSH to HTTPS

---

README.md
build.gradle
src/main/resources/META-INF/plugin.xml

Add plugin support to IDEA 2017

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

This PR fixes issues in code completion.

Fix issues in code completion

---

src/main/java/org/ballerinalang/plugins/idea/codeinsight/editoractions/BallerinaQuoteHandler.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaEnterBetweenBracesHandler.java

Add string split support by Enter key

---

src/main/java/org/ballerinalang/plugins/idea/marker/BallerinaRecursiveCallMarkerProvider.java

Fix multiple markers issue

---

src/test/java/BallerinaRecursiveCallMarkerTest.java
src/test/resources/testData/recursiveMarker/Function1.bal
src/test/resources/testData/recursiveMarker/Function2.bal
src/test/resources/testData/recursiveMarker/Function3.bal
src/test/resources/testData/recursiveMarker/Function4.bal
src/test/resources/testData/recursiveMarker/Function5.bal

Add tests to recursive call marker

---

src/main/java/org/ballerinalang/plugins/idea/codeinsight/daemon/impl/BallerinaAnnotator.java

This PR fixes the constants not annotating issue and add helper methods to reduce `annotate` method complexity.

Fix consts not annotating issue

---

src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaEnterBetweenBracesHandler.java

Fix issue in enter handler

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix packages not resolving properly issue

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/highlighter/BallerinaSyntaxHighlighter.java

Update token highlighting

---

src/main/java/org/ballerinalang/plugins/idea/run/configuration/BallerinaConsoleFolding.java
src/main/java/org/ballerinalang/plugins/idea/run/configuration/BallerinaRunConfigurationProducerBase.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaEnvironmentUtil.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkUtil.java
src/main/java/org/ballerinalang/plugins/idea/util/BallerinaUtil.java

This PR fixes issues encountered in Windows OS.

Fix issues in Windows OS

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/documentation/BallerinaDocumentationProvider.java

Add parameters to lookups

---

src/main/java/org/ballerinalang/plugins/idea/actions/BallerinaTemplatePropertiesProvider.java
src/main/resources/fileTemplates/internal/Ballerina Application.bal.ft
src/main/resources/fileTemplates/internal/Ballerina File.bal.ft
src/main/resources/fileTemplates/internal/Ballerina File.bal.html

This PR will update file templates to fix issues in adding package name to new files.
Resolves #213

Update file templates

---

src/main/gen/org/ballerinalang/plugins/idea/grammar/BallerinaBaseListener.java
src/main/gen/org/ballerinalang/plugins/idea/grammar/BallerinaBaseVisitor.java
src/main/gen/org/ballerinalang/plugins/idea/grammar/BallerinaLexer.java
src/main/gen/org/ballerinalang/plugins/idea/grammar/BallerinaListener.java
src/main/gen/org/ballerinalang/plugins/idea/grammar/BallerinaParser.java
src/main/gen/org/ballerinalang/plugins/idea/grammar/BallerinaVisitor.java
src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/BallerinaTypes.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaBlock.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaFormattingModelBuilder.java
src/main/java/org/ballerinalang/plugins/idea/grammar/Ballerina.g4
src/main/java/org/ballerinalang/plugins/idea/psi/ForkJoinStatementNode.java
src/main/java/org/ballerinalang/plugins/idea/template/BallerinaCodeContextType.java
src/main/resources/META-INF/plugin.xml
src/main/resources/liveTemplates/Ballerina.xml
src/test/java/BallerinaCompletionTest.java

Add fork-join, worker live templates

---

src/main/java/org/ballerinalang/plugins/idea/codeinsight/daemon/impl/BallerinaAnnotator.java
src/main/java/org/ballerinalang/plugins/idea/psi/BallerinaFile.java
src/main/java/org/ballerinalang/plugins/idea/psi/CallableUnitBodyNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/FunctionDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/ActionInvocationReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

This PR updates reference resolving of functions, connectors, etc.

Update reference resolving

---

src/main/java/org/ballerinalang/plugins/idea/project/BallerinaProjectExtension.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkService.java
src/main/resources/META-INF/plugin.xml

This PR will add a new Project Extension which will update the SDK of modules.
Resolve #289

Add project extension

---

src/main/java/org/ballerinalang/plugins/idea/completion/FunctionCompletionInsertHandler.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaFormattingModelBuilder.java
src/test/java/BallerinaCompletionTest.java

This PR fixes operators not formatting properly issue.

Fix formatting issue

---

src/main/java/org/ballerinalang/plugins/idea/project/BallerinaProjectExtension.java

Fix module SDK not updating issue

---

src/main/resources/liveTemplates/Ballerina.xml

Remove unsupported live templates

---

src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaEnterBetweenBracesHandler.java

This PR will fix the issue of `}` not indenting properly.
Resolves #302

Fix indent issue

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/test/java/BallerinaCompletionTest.java

Fix constant types suggesting issue

---

src/main/resources/liveTemplates/Ballerina.xml

Add transaction live template

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/test/java/BallerinaCompletionTest.java

This PR adds functions as suggestions to global variable values section.
Resolves #303

Adds suggestions for global variable values

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/test/java/BallerinaCompletionTest.java

Fix immediate variable not suggesting issue

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/test/java/BallerinaCompletionTest.java

Fix package, import not suggesting properly

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/test/java/BallerinaCompletionTest.java

Fix common keywords not suggesting issue

---

src/main/java/org/ballerinalang/plugins/idea/codeinsight/highlighting/BallerinaBraceMatcher.java
src/main/java/org/ballerinalang/plugins/idea/codeinsight/highlighting/BallerinaPairedBraceMatcher.java
src/main/resources/META-INF/plugin.xml

Removing <,> from brace matcher

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/documentation/BallerinaDocumentationProvider.java

Fix return types not available issue

---

src/main/resources/META-INF/plugin.xml

This PR updates plugin version to v0.8.6 and updates change notes.

Update plugin xml

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix parameters not resolving issue

---

src/main/java/org/ballerinalang/plugins/idea/psi/ActionDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/AnnotationDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ConnectorDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ConstantDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/FieldDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/FunctionDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/GlobalVariableDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ParameterNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ResourceDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/ServiceDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/StructDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/VariableDefinitionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaItemPresentation.java

Add item presentations to definitions

---

src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

Fix find usage issue in annotations

---

src/main/java/org/ballerinalang/plugins/idea/documentation/BallerinaDocumentationProvider.java
src/test/resources/testData/documentation/Connector1.bal
src/test/resources/testData/documentation/Connector2.bal
src/test/resources/testData/documentation/Connector3.bal
src/test/resources/testData/documentation/Connector4.bal

Fix action documentation issue

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/codeinsight/daemon/impl/BallerinaAnnotator.java
src/main/java/org/ballerinalang/plugins/idea/highlighter/BallerinaColorSettingsPage.java
src/main/java/org/ballerinalang/plugins/idea/highlighter/BallerinaSyntaxHighlighter.java
src/main/java/org/ballerinalang/plugins/idea/highlighter/BallerinaSyntaxHighlightingColors.java

Add query/path param highlight support

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaModuleBuilder.java

Add package creation support

---

src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaModuleEditorsProvider.java
src/main/resources/META-INF/plugin.xml

Add module settings

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/AdjustPackageNameFix.java
src/main/java/org/ballerinalang/plugins/idea/codeInspection/WrongPackageStatementInspection.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaElementFactory.java
src/main/resources/META-INF/plugin.xml

Add package inspection

---

src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaBlock.java
src/test/resources/testData/formatting/Statement-after.bal
src/test/resources/testData/formatting/Statement.bal
src/test/resources/testData/formatting/Transaction-after.bal

Fix map key value formatting issue

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java

Increase priority of imported packages

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/PackageNameReference.java

Fix issue in alias resolving

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/WrongPackageStatementInspection.java

Fix issue in package inspection

---

build.gradle

Update IDEA version

---

src/main/resources/META-INF/plugin.xml

Change package inspection level

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix SDK imports not available issue

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/AdjustPackageNameFix.java
src/main/java/org/ballerinalang/plugins/idea/codeInspection/WrongPackageStatementInspection.java

Improve package declaration inspection

---

src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

Fix variable referencing issue

---

src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkUtil.java
src/main/java/org/ballerinalang/plugins/idea/util/BallerinaExecutor.java

Add ballerina sub module run support

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaIcons.java
src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/psi/JoinConditionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/TriggerWorkerNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/WorkerBodyNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/WorkerDeclarationNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/WorkerReplyNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaItemPresentation.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaRootPresentation.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaStructureViewElement.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaStructureViewModel.java
src/main/java/org/ballerinalang/plugins/idea/structureview/BallerinaStructureViewRootElement.java
src/test/java/completion/BallerinaWorkerSuggestionsTest.java

This PR adds worker suggestion support.
* In Join conditions
* In Worker trigger statements
* In Worker reply statements

Add worker suggestion support

---

src/main/resources/META-INF/plugin.xml

Fix Ballerina template issue

---

src/main/resources/META-INF/plugin.xml

This PR updates change notes in plugin.xml.

Update change notes for v0.8.7

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/AdjustPackageNameFix.java
src/main/java/org/ballerinalang/plugins/idea/codeInspection/BallerinaImportPackageQuickFix.java
src/main/java/org/ballerinalang/plugins/idea/codeinsight/imports/BallerinaAutoImportConfigurable.java
src/main/java/org/ballerinalang/plugins/idea/codeinsight/imports/BallerinaCodeInsightSettings.java
src/main/java/org/ballerinalang/plugins/idea/configuration/BallerinaConfigurableProvider.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkService.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaSdkUtil.java
src/main/resources/META-INF/plugin.xml

This PR fixes small issues in auto imports and adds auto import configuration to settings window.
Auto import is disabled by default. This is done to make sure user does not run into any issues while using this auto import feature. They can enable it if they want.
Resolves #433
Resolves #435

Add auto import configurations to settings

---

build.gradle

Remove unnecessary antlr dependency

---

src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaDebugProcess.java
src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaWebSocketConnector.java
src/main/java/org/ballerinalang/plugins/idea/debugger/client/WebSocketClient.java

This PR fixes the memory leak in the debugger.
Resolves #448

Fix memory leak issue in debugger

---

src/main/java/org/ballerinalang/plugins/idea/inspections/WrongModuleTypeNotificationProvider.java
src/main/resources/META-INF/plugin.xml

Add new notification provider

---

src/main/java/org/ballerinalang/plugins/idea/codeinsight/daemon/impl/BallerinaProjectSdkSetupValidator.java

Update SDK validator logic

---

src/main/antlr/org/ballerinalang/plugins/idea/grammar/Ballerina.g4
src/main/java/org/ballerinalang/plugins/idea/BallerinaIcons.java
src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/codeInsight/daemon/impl/BallerinaAnnotator.java
src/main/java/org/ballerinalang/plugins/idea/codeInspection/BallerinaUnresolvedReferenceInspection.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/NamespaceDeclarationNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/XmlAttribNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameSpaceReference.java
src/main/java/org/ballerinalang/plugins/idea/usage/BallerinaFindUsageProvider.java

This PR will update the xml grammar to match the Ballerina grammar.

Update xml grammar

---

src/main/resources/liveTemplates/Ballerina.xml
src/test/java/org/ballerinalang/editor/BallerinaLiveTemplateTest.java

This PR updates the function live template to improve user experience.

Update function live template

---

src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/FieldReference.java

Fix error variable not resolving issue in try-catch blocks

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnusedConstantInspection.java
src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnusedGlobalVariableInspection.java
src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnusedParameterInspection.java
src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnusedVariableInspection.java
src/main/resources/META-INF/plugin.xml

This PR will add unused variables, global variables, parameters, constants inspection support.
Resolves #490 
Resolves #492 
Resolves #493 
Resolves #494

Add new inspections

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/BallerinaUnresolvedReferenceInspection.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

The unresolved reference inspection will also inspect unresolved variables, functions, connectors, etc.
Resolves #495

Update unresolved references

---

src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaDebugProcess.java
src/main/java/org/ballerinalang/plugins/idea/debugger/client/WebSocketClient.java

This PR fixes a connection not closing issue in remote debugging.
Resolves #506

Fix issues in remote debugging

---

src/main/java/org/ballerinalang/plugins/idea/runconfig/application/BallerinaApplicationRunningState.java

This PR update the run configurations to match the changes done in the v0.90.
Resolves #508

Update run configurations

---

src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

This PR enables resolving name reference to a function since the lambda functions are available.

Update name reference

---

src/main/resources/META-INF/plugin.xml
src/main/resources/fileTemplates/internal/Ballerina Connector.bal.ft
src/main/resources/fileTemplates/internal/Ballerina Connector.bal.html

Resolves #462 
Resolves #517
Resolves #518

Add connector sample file

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnusedVariableInspection.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/usage/BallerinaFindUsageProvider.java

Resolves #515 
Resolves #524 
Resolves #525

Fix issues related to var assignment 

---

src/main/java/org/ballerinalang/plugins/idea/codeInsight/daemon/impl/BallerinaAnnotator.java

Fix path params not highlighting issue

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/FunctionInvocationInspection.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/FunctionInvocation.html

This PR adds a new inspection to inspect function invocations which will identify mismatches in number of arguments provided to the function and number of required parameters.
Resolves #541

Add new function invocation inspection

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnresolvedReferenceInspection.java

Fix unresolved reference issue in packages

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaKeywordsCompletionContributor.java
src/test/java/org/ballerinalang/completion/BallerinaCompletionTest.java

Add typeof, lengthof keywords

---

src/main/resources/liveTemplates/BallerinaHidden.xml

Add xmlns hidden template

---

src/main/resources/fileTemplates/internal/Ballerina Connector.bal.ft

Update connector file template

---

src/main/resources/liveTemplates/BallerinaHidden.xml
src/test/java/org/ballerinalang/completion/BallerinaCompletionTest.java

Update worker hidden template

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaASTFactory.java
src/main/java/org/ballerinalang/plugins/idea/codeInsight/completion/SkipAutoPopupInFloatingPointLiterals.java
src/main/java/org/ballerinalang/plugins/idea/psi/FloatingPointLiteral.java
src/main/resources/META-INF/plugin.xml

Add new completion confidence to skip auto popup in floats

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnusedVariableInspection.java

Fix ignored variables highlighting issue

---

src/main/java/org/ballerinalang/plugins/idea/psi/injector/LanguageInjectorUtils.java

Update language injection

---

src/main/resources/liveTemplates/Ballerina.xml

Add new live template

---

src/main/java/org/ballerinalang/plugins/idea/marker/BallerinaRecursiveCallMarkerProvider.java

Fix issue in recursive call marker

---

src/main/antlr/org/ballerinalang/plugins/idea/grammar/BallerinaLexer.g4
src/main/java/org/ballerinalang/plugins/idea/BallerinaTypes.java
src/main/java/org/ballerinalang/plugins/idea/codeInsight/editoractions/BallerinaQuoteHandler.java
src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaEnterBetweenBracesHandler.java

This PR adds multi-line string support and multi-line backticked template support.

Add multi line string/backticked template support

---

src/main/resources/fileTemplates/internal/Ballerina Service.bal.ft

Update service file template

---

src/main/antlr/org/ballerinalang/plugins/idea/grammar/BallerinaParser.g4
src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/psi/TypeCastNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/TypeConversionNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/FieldReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/StructKeyReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/StructValueReference.java

Resolves #569 
Resolves #594
Resolves #595

Improve structs field suggesting

---

src/main/java/org/ballerinalang/plugins/idea/codeInsight/daemon/impl/BallerinaAnnotator.java

Fix query, path parameter highlighting issue

---

src/main/java/org/ballerinalang/plugins/idea/formatter/BallerinaBlock.java
src/test/resources/testData/formatting/ForkJoin-after.bal
src/test/resources/testData/formatting/ForkJoin.bal
src/test/resources/testData/formatting/Statement-after.bal
src/test/resources/testData/formatting/Statement.bal

Fix formatting issues

---

src/main/antlr/org/ballerinalang/plugins/idea/grammar/BallerinaParser.g4

Fix while statement scope issue

---

src/main/java/org/ballerinalang/plugins/idea/documentation/BallerinaDocumentationProvider.java

Fix method signature issue

---

src/main/java/org/ballerinalang/plugins/idea/runconfig/BallerinaRunConfigurationProducerBase.java
src/main/java/org/ballerinalang/plugins/idea/util/BallerinaUtil.java

Fix working directory not identifying properly issue

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/WrongPackageStatementInspection.java

Remove package declaration inspection in non-Ballerina modules

---

src/main/java/org/ballerinalang/plugins/idea/editor/BallerinaParameterInfoHandler.java

Fix parameter info not showing issue in connectors

---

src/main/java/org/ballerinalang/plugins/idea/project/BallerinaProjectStructureDetector.java
src/main/resources/META-INF/plugin.xml

When we create a new project from existing source, Intellij will suggest Ballerina module type if the selected directory or sub directory contain any .bal files.
Resolves #545
Resolves #590

Add a project structure detector

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix struct fields not resolving issue

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/BallerinaTypes.java
src/main/java/org/ballerinalang/plugins/idea/codeInsight/daemon/impl/BallerinaAnnotator.java
src/main/java/org/ballerinalang/plugins/idea/highlighter/BallerinaSyntaxHighlightingColors.java
src/main/java/org/ballerinalang/plugins/idea/psi/StringTemplateContentNode.java

Add string template highlight support

---

src/main/resources/liveTemplates/BallerinaHidden.xml
src/test/java/org/ballerinalang/completion/BallerinaCompletionTest.java

Update fork join templates

---

src/main/java/org/ballerinalang/plugins/idea/runconfig/BallerinaRunUtil.java
src/main/java/org/ballerinalang/plugins/idea/runconfig/ui/BallerinaApplicationSettingsEditor.java

Fix working directory browse button disabled issue

---

README.md

Update supported platform versions in the readme

---

src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaStackFrame.java
src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaXValueGroup.java
src/main/java/org/ballerinalang/plugins/idea/runconfig/BallerinaConsoleFolding.java

Update debugger variable grouping

---

src/main/resources/META-INF/plugin.xml

Update unused inspection problem type

---

src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

This PR fixes the name reference completions becoming slower issue.

Fix name references completion slow issue

---

src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaDebugProcess.java
src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaStackFrame.java

Fix debug hit file finding issue

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

This PR fixes an issue in the code where an Index Out of Bound exception can be occurred in runtime.

Fix possible Index Out of Bound exception issue

---

src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaPathModificationTracker.java

Update Ballerina repository src directory

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/FunctionInvocationInspection.java

Fix issue in function parameter inspection

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/editor/BallerinaParameterInfoHandler.java
src/main/java/org/ballerinalang/plugins/idea/psi/AnonStructTypeNameNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/ActionInvocationReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/StructKeyReference.java

Resolves #688 
Resolves #690 
Resolves #691

Update anonymous struct support

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/editor/BallerinaParameterInfoHandler.java
src/main/java/org/ballerinalang/plugins/idea/psi/AnonStructTypeNameNode.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/ActionInvocationReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/AnnotationReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/StructKeyReference.java

Fix doc annotations not suggesting issue

---

src/main/resources/fileTemplates/internal/Ballerina Connector.bal.ft

change connector file template to reflect ballerina 0.95.0 changes

---

src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/test/java/org/ballerinalang/completion/BallerinaConstantCompletionTest.java
src/test/java/org/ballerinalang/completion/BallerinaGlobalVariableCompletionTest.java
src/test/java/org/ballerinalang/psi/vars/BallerinaResolveGlobalVariableTest.java

Fix private variable suggesting issue

---

src/main/resources/fileTemplates/internal/Ballerina Service.bal.ft

Change service template to reflect ballerina 0.95.3

---

src/main/java/org/ballerinalang/plugins/idea/runconfig/application/BallerinaApplicationRunningState.java

Update Ballerina debug flag

---

build.gradle
src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaXValueGroup.java

Some functionality in debugging is not available in earlier versions.

Change Ballerina version in build script

---

src/main/resources/liveTemplates/Ballerina.xml

Update transaction template

---

src/main/resources/META-INF/plugin.xml

Fix inspection short name issue

---

src/main/java/org/ballerinalang/plugins/idea/runconfig/BallerinaRunConfigurationWithMain.java
src/main/java/org/ballerinalang/plugins/idea/runconfig/remote/BallerinaRemoteConfiguration.java

Add default host and port

---

src/main/java/org/ballerinalang/plugins/idea/psi/references/ConnectorReference.java
src/test/java/org/ballerinalang/completion/BallerinaCompletionTest.java

Fix connector completion issue in endpoints

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaParserDefinition.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaCompletionUtils.java
src/main/java/org/ballerinalang/plugins/idea/completion/BallerinaKeywordsCompletionContributor.java
src/main/java/org/ballerinalang/plugins/idea/psi/FailedClauseNode.java

Fix return keyword not available issue

---

src/main/java/org/ballerinalang/plugins/idea/debugger/BallerinaStackFrame.java

Fix debug hits in Ballerina SDK not showing issue

---

src/main/resources/liveTemplates/Ballerina.xml
src/test/java/org/ballerinalang/editor/BallerinaLiveTemplateTest.java

Add new transformer live template

---

src/main/java/org/ballerinalang/plugins/idea/codeInsight/daemon/impl/BallerinaAnnotator.java

Remove query param annotating

---

src/main/java/org/ballerinalang/plugins/idea/psi/references/NameSpaceReference.java

Fix namespace reference issue

---

src/main/resources/liveTemplates/BallerinaHidden.xml
src/test/java/org/ballerinalang/completion/BallerinaHiddenTemplateCompletionTest.java

Fix else statement template issue

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/NameReference.java

Fix constant and global variable suggesting issue

---

src/main/resources/liveTemplates/Ballerina.xml
src/test/java/org/ballerinalang/editor/BallerinaLiveTemplateTest.java

Update resource live template

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix auto import leading space issue

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/psi/references/FieldReference.java

Fix struct fields not completing issue

---

README.md

Remove transaction related note

---

src/main/java/org/ballerinalang/plugins/idea/project/BallerinaProjectStructureDetector.java

Fix project root always identifying as Ballerina issue

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/BallerinaUnresolvedReferenceInspection.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix '_' suggesting in code completion

---

src/main/java/org/ballerinalang/plugins/idea/documentation/BallerinaDocumentationProvider.java
src/main/java/org/ballerinalang/plugins/idea/editor/BallerinaParameterInfoHandler.java

Format parameters in lookups

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaConstants.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java
src/main/java/org/ballerinalang/plugins/idea/sdk/BallerinaPathModificationTracker.java
src/main/java/org/ballerinalang/plugins/idea/util/BallerinaUtil.java

Fix user repository suggesting issues

---

src/main/java/org/ballerinalang/plugins/idea/lang/BallerinaImportOptimizer.java
src/main/java/org/ballerinalang/plugins/idea/psi/ImportDeclarationNode.java
src/main/resources/META-INF/plugin.xml

Add import optimizer

---

src/main/java/org/ballerinalang/plugins/idea/BallerinaConstants.java
src/main/java/org/ballerinalang/plugins/idea/BallerinaExternalAnnotator.java
src/main/java/org/ballerinalang/plugins/idea/project/BallerinaProjectExtension.java

Update external annotator

---

src/main/java/org/ballerinalang/plugins/idea/actions/BallerinaCreateFileAction.java
src/main/resources/META-INF/plugin.xml
src/main/resources/fileTemplates/internal/Ballerina WebSocket.bal.ft
src/main/resources/fileTemplates/internal/Ballerina WebSocket.bal.html

Add ws template

---

src/main/java/org/ballerinalang/plugins/idea/codeInspection/UnusedVariableInspection.java
src/main/java/org/ballerinalang/plugins/idea/psi/IdentifierPSINode.java
src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix unused variable inspection issue

---

src/main/java/org/ballerinalang/plugins/idea/psi/impl/BallerinaPsiImplUtil.java

Fix issue in package resolving

---

src/main/java/org/ballerinalang/plugins/idea/actions/BallerinaCreateFileAction.java
src/main/resources/META-INF/plugin.xml
src/main/resources/fileTemplates/internal/Ballerina Test.bal.ft
src/main/resources/fileTemplates/internal/Ballerina Test.bal.html

Add Ballerina test file template

---

README.md

Reverts ballerina-lang/plugin-intellij#810

Revert "Add banner"

---

README.md

Reverts ballerina-lang/plugin-intellij#811

Revert "Revert "Add banner""
